services:
  - type: web
    name: portal-juegos-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portal_juegos_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
    healthCheckPath: /api/games/

databases:
  - name: portal_juegos_db
    databaseName: portal_juegos
    user: portal_user